# Generated by Django 4.2 on 2023-04-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('decription', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
