# Generated by Django 4.2 on 2023-05-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja', '0003_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('dania_glowne', 'Dania Główne'), ('napoje', 'Napoje'), ('przystawki', 'Przystawki')], max_length=15),
        ),
    ]
